language: objective-c
osx_image: xcode8.1
cache: 
  directories:
    - vendor/bundle
    - Pods
before_install:
  - gem install bundler
install:
  - brew update && (brew upgrade xctool || true) && xctool --version
  - bundle install -j4 --path=vendor/bundle --binstubs=vendor/bin
  - cd Example && bundle exec pod install
xcode_workspace:  Example/StringValidatorExample.xcworkspace
xcode_scheme: StringValidatorExample
xcode_sdk: iphonesimulator
env:
  - XCODE_SDK=iphonesimulator8.4
  - XCODE_SDK=iphonesimulator9.3
  - XCODE_SDK=iphonesimulator10.1
